### ISSUE TITLE
cant use World.init(getApplication());

### ISSUE THREAD

**Issue by jomarierafa** [blongho/worldCountryData#3] opened 2019-09-04 08:41 UTC
im using androidx and kotlin
i can't use World

the build is successful
implementation 'com.github.blongho:world-country-data:1.3-alpha'

**Comment by olehka** [comment] 2019-09-26 17:31
I have the same problem :(

**Comment by blongho** [comment] 2019-09-27 07:00
Will try to **fix**  in the days ahead...

**Comment by blongho** [comment] 2019-11-16 03:21
Hi, @jomarierafa The issue is now fixed with v1.4-beta

**Closed as completed by blongho** 2019-11-16 03:21 UTC
Labels: bug
