### ISSUE TITLE
[JITPACK] Version 1.3 unavailable

### ISSUE THREAD

**Issue by 4rthurRousseau** [blongho/worldCountryData#4] opened 2019-10-27 01:00 UTC
Hello there,

I wanted to upgrade to 1.3 but I noticed that it isn't available on Jitpack.
The build logs shows an error trying to run the _publish.gradle_ script.

I couldn't find this file in the repository, should it be there or is that a Jitpack generated file ?

**Comment by blongho** [comment] 2019-10-30 18:59
Hi @4rthurRousseau , please use revert to v1.1.0. This is the only stable build from jitpack. I have tested the builds without the local libraries and it fails too. Will have to investigate why versions greater than v1.1.0 do not build correctly. 

Your can watch the repository for any future updates by starring so that you get notified if some change happen.

**Comment by blongho** [comment] 2019-11-16 03:20
Hi, @4rthurRousseau The issue is now fixed with v1.4-beta

**Closed as completed by blongho** 2019-11-16 03:20 UTC
